spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/home_maintenance_db
spring.datasource.username=${POSTGRES_USER:home_maintenance_user}
spring.datasource.password=${POSTGRES_PASSWORD:home_maintenance_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000